version: '2'

services:
  games-api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: games-api
    ports:
      - 5000:5000
    volumes:
      - ./src/api/src:/srv/src/api/src
    entrypoint: /srv/src/api/entrypoint.sh

  games-ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    container_name: games-ui
    ports:
      - 3000:3000
    volumes:
      - ./src/ui/src:/srv/src/ui/src
    entrypoint: /srv/src/ui/entrypoint.sh

  postgres:
    image: postgres:10.6
    container_name: postgres
    environment:
      - POSTGRES_DB=games
      - POSTGRES_USER=wombat
      - POSTGRES_PASSWORD=1wombat2
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    # uncomment to see all queries
    # command: ["postgres", "-c", "log_statement=all"]
